// src/lib/registry.js
// Add/edit objects here. All are .glb models + an audio file.

export const objects = [
  {
    id: 'dog',
    modelUrl: '/models/dog.glb',
    soundUrl: '/sounds/dog.flac',
    rotation: [0, 0, 0],
    scale: [1.1, 1.1, 1.1],
  },
  {
    id: 'crunch',
    modelUrl: '/models/crunch.glb',
    soundUrl: '/sounds/crunch.wav',
    rotation: [0, Math.PI / 8, 0],
    scale: [2, 2, 2],
  },
  {
    id: 'footsteps',
    modelUrl: '/models/footsteps.glb',
    soundUrl: '/sounds/footsteps.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [5, 5, 5],
  },
  {
    id: 'bird',
    modelUrl: '/models/bird.glb',
    soundUrl: '/sounds/bird.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [1.1, 1.1, 1.1],
  },
  {
    id: 'heart',
    modelUrl: '/models/heart.glb',
    soundUrl: '/sounds/heart.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [40, 40, 40],
  },
  {
    id: 'telephone',
    modelUrl: '/models/telephone.glb',
    soundUrl: '/sounds/telephone.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [1.5, 1.5, 1.5],
  },
  {
    id: 'earthquake',
    modelUrl: '/models/earthquake.glb',
    soundUrl: '/sounds/earthquake.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [1.2, 1.2, 1.2],
  },
  {
    id: 'motorcycle',
    modelUrl: '/models/motorcycle.glb',
    soundUrl: '/sounds/motorcycle.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'hookah',
    modelUrl: '/models/hookah.glb',
    soundUrl: '/sounds/hookah.wav',
    position: [0, -12, 0],
    rotation: [-Math.PI, 0, 0],
    scale: [10, 10, 10],
  },
  {
    id: 'waterdrop',
    modelUrl: '/models/waterdrop.glb',
    soundUrl: '/sounds/waterdrop.wav',
    position: [15, 5, 0],
    rotation: [0, -Math.PI / 12, 0],
    scale: [25, 25, 25],
  },
  {
    id: 'wind-tree',
    modelUrl: '/models/wind-tree.glb',
    soundUrl: '/sounds/wind-tree.wav',
    rotation: [0, -Math.PI / 12, 0],
    scale: [3, 3, 3],
  },
  {
    id: 'cat',
    modelUrl: '/models/cat.glb',
    soundUrl: '/sounds/cat.wav',
    position: [25, 0.5, 15],
    rotation: [0, -Math.PI / 12, 0],
    scale: [1, 1, 1],
  },
  {
    id: 'tram',
    modelUrl: '/models/tram.glb',
    soundUrl: '/sounds/tram.wav',
    position: [-50, 1, 10],
    rotation: [0, -Math.PI / 12, 0],
    scale: [5, 5, 5],
  },
  {
    id: 'snake',
    modelUrl: '/models/snake.glb',
    soundUrl: '/sounds/snake.wav',
    position: [70, 1, 0],
    rotation: [0, -Math.PI / 12, 0],
    scale: [4, 4, 4],
  },
  {
    id: 'grasshopper',
    modelUrl: '/models/grasshopper.glb',
    soundUrl: '/sounds/grasshopper.wav',
    position: [-20, -38.5, -3],
    rotation: [0, -Math.PI / 12, 0],
    scale: [.02, .02, .02],
  }
];
